CREATE TABLE IF NOT EXISTS artists (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, genre TEXT NOT NULL, color TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tracks (id INTEGER PRIMARY KEY, title TEXT NOT NULL, artist_id INTEGER NOT NULL REFERENCES artists(id), duration INTEGER NOT NULL, accent TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_tracks_artist ON tracks(artist_id);
