import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8787';
const demo = { artists:[{id:1,name:'Aurora Lane',genre:'Indie eletrônico',color:'#8b5cf6'},{id:2,name:'Maré Alta',genre:'Pop alternativo',color:'#14b8a6'},{id:3,name:'Norte Solar',genre:'Instrumental',color:'#f97316'}], tracks:[{id:1,title:'Horizonte',artist_id:1,artist:'Aurora Lane',duration:214,accent:'#8b5cf6'},{id:2,title:'Pulso Calmo',artist_id:2,artist:'Maré Alta',duration:187,accent:'#14b8a6'},{id:3,title:'Luz de Janeiro',artist_id:3,artist:'Norte Solar',duration:241,accent:'#f97316'},{id:4,title:'Depois da Chuva',artist_id:1,artist:'Aurora Lane',duration:203,accent:'#a855f7'}] };
const fmt = s => `${Math.floor(s / 60)}:${String(s % 60).padStart(2,'0')}`;
function App() {
 const [data,setData]=useState(demo), [source,setSource]=useState('modo demonstração'), [active,setActive]=useState(null), [query,setQuery]=useState('');
 useEffect(()=>{ fetch(`${API}/api/catalog`).then(r=>r.ok?r.json():Promise.reject()).then(d=>{setData(d);setSource('catálogo D1');}).catch(()=>{});},[]);
 const tracks=data.tracks.filter(t=>`${t.title} ${t.artist}`.toLowerCase().includes(query.toLowerCase()));
 return <main><nav><a className="brand" href="#top">sound<span>wave</span></a><span className="pill">{source}</span></nav><section className="hero" id="top"><p className="eyebrow">MÚSICA INDEPENDENTE · DEMO AUTORAL</p><h1>Seu próximo som<br/><em>começa aqui.</em></h1><p>Um catálogo musical criado para demonstrar React, Vite, Cloudflare Workers e D1 — sem conteúdo protegido de terceiros.</p><a href="#catalog" className="cta">Explorar catálogo <b>→</b></a></section><section className="catalog" id="catalog"><div className="section-head"><div><p className="eyebrow">CATÁLOGO</p><h2>Faixas em destaque</h2></div><input aria-label="Buscar faixas" placeholder="Buscar faixa ou artista" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="layout"><div className="tracks">{tracks.map((t,i)=><button className={`track ${active?.id===t.id?'selected':''}`} key={t.id} onClick={()=>setActive(t)}><span className="track-number">{String(i+1).padStart(2,'0')}</span><span className="cover" style={{background:t.accent}}></span><span className="track-info"><strong>{t.title}</strong><small>{t.artist}</small></span><span>{fmt(t.duration)}</span></button>)}</div><aside><p className="eyebrow">ARTISTAS</p>{data.artists.map(a=><div className="artist" key={a.id}><i style={{background:a.color}}></i><span><strong>{a.name}</strong><small>{a.genre}</small></span></div>)}</aside></div></section><footer>SoundWave · Projeto demonstrativo autoral · Dados persistidos em Cloudflare D1</footer>{active&&<div className="player"><span className="cover mini" style={{background:active.accent}}></span><span><strong>{active.title}</strong><small>{active.artist}</small></span><button onClick={()=>setActive(null)}>Encerrar</button></div>}</main>
}
createRoot(document.getElementById('root')).render(<App/>);
